### PR TITLE
Configured the subdomain template for landing pages, only.

### PR DESCRIPTION
**Pull request by davestys**
Resolved a conflict in the email-web-subdomain.json template, and renamed it `aweber.com.web-subdomain.json`.

### CODE REVIEW

**Review by pawel-kow — CHANGES_REQUESTED** [review]
AssertionError: File name aweber.com.web-subdomain.json not matching the pattern. Expected aweber.com.email-web-subdomain.json
Please either adjust `serviceId` or file name.

**Comment by davestys** [comment]
AWeber team is reviewing and testing these changes. Upon success, I'll change the status from Draft to Ready.

**Comment by pawel-kow** [comment]
> AWeber team is reviewing and testing these changes. Upon success, I'll change the status from Draft to Ready.

All good. I did not notice the draft status.

**Comment by davestys** [comment]
Not a problem. I love that you're always quick to respond to PRs. Thanks @pawel-kow.

**Comment by aremm** [comment]
👍

**Comment by davestys** [comment]
@pawel-kow once this is merged, you are all clear to install at IONOS. Thanks

**Review by pawel-kow — COMMENTED** [review]
All OK

**Pull request merged**
