### PR TITLE
Template for Sentro.PH

### PR DESCRIPTION
**Pull request by w-ubx**

### CODE REVIEW

**Comment by w-ubx** [comment]
Changed this to draft as this is still Work In Progress and I'm not sure if it's gonna work. Hope you can enlighten me on the changes needed to do to make this work. 
Thanks a lot!

**Comment by pawel-kow** [comment]
Hi @w-ubx, you may test your template upfront using this project: https://github.com/Domain-Connect/DomainConnectApplyZone

**Comment by w-ubx** [comment]
Great! Thanks a lot!

**Comment by rphilip** [comment]
@w-ubx  Our DNS team is good with the template as is.  If you are satisfied with your test as Pawel directed, please update the status of this PR and we can move forward

**Comment by w-ubx** [comment]
hi @rphilip , i've already changed the status for merging. thank you!

**Review by pawel-kow — APPROVED** [review]
OK from my POV

**Comment by pawel-kow** [comment]
@w-ubx , thanks, merged now. Please let us know if you'd like to get listed on domainconnect.org.
If yes pls reach out via contact form on https://www.domainconnect.org/inquiries/
We'd need logo, contact email address and landing URL for your service.

**Pull request merged**
