### PR TITLE
Update tinkerhost.net.tinkermail.json to version 2

### PR DESCRIPTION
**Pull request by greenreader9**
Adds support for TXT record _dmarc. Does not add or change any variables.

### CODE REVIEW

**Comment by greenreader9** [comment]
Is there a SPFM-like record type that can be used for DMARC records as they are also restricted to one per hostname?

**Comment by pawel-kow** [comment]
@greenreader9 setting `txtConflictMatchingMode` to `All` is intended for this purpose. It's not (yet) widely supported by DNS providers.
Other (intermediate) option would be to put CNAME there which would always wipe anything else.

**Comment by greenreader9** [comment]
@pawel-kow, if txtConflictMatchingMode and txtConflictMatchingPrefix were added to the record and the DNS provider does not support it, I would assume it would just get overridden by the provider?

I don't want to override a users DMARC record if they already have one in place (especially since my default is "none"), and placing a CNAME record to a DMARC record on a domain where a DMARC record is already in place probably constitutes multiple DMARC records for the domain.

**Comment by pawel-kow** [comment]
> @pawel-kow, if txtConflictMatchingMode and txtConflictMatchingPrefix were added to the record and the DNS provider does not support it, I would assume it would just get overridden by the provider?

No, unfortunately not. They will just add a second record.
CNAME would guarantee a replacement as CNAME cannot coexist with any other record, so the provider will always replace.
 
> I don't want to override a users DMARC record if they already have one in place (especially since my default is "none"), and placing a CNAME record to a DMARC record on a domain where a DMARC record is already in place probably constitutes multiple DMARC records for the domain.

The solution to that would be to define a group for DMARC and apply this group only if DMARC is not yet present. This would also solve the problem of the duplicate if the intention is to only add DMARC if there is none present.
I would also suggest adding essential=OnApply so that DMARC can be updated/replaced without dropping the whole template.

**Comment by greenreader9** [comment]
@pawel-kow , updated the record to include both 'essential' as well as 'txtConflictMatchingMode' for supported providers

**Comment by kerolasa** [comment]
Would it be possible to squash commits 5feaa01 and 4288bb3 together.

**Review by pawel-kow — APPROVED** [review]
lgtm!

**Pull request merged**
