### PR TITLE
dnsdad template

### PR DESCRIPTION
**Pull request by sagartankw3nuts**
We have a podcasting platform

In the podcasting platform where our customers create websites using a custom drag & drop builder tool feature on our platform. Our customer who created a website using our tool is facing difficulty in DNS mapping manually. So, we want to add functionality that deal with the DNS providers from and change the DNS.

I have 2 servers
- dnsdad.shop
- podup.com (Podcasting platform)

What I’ll do and want to do,
- I’ll create an API of dnsdad.shop and whenever the customers wants to change the DNS, the podup will use the API and through the Dnsdad.shop the request will be sent to the DNS Providers.

### CODE REVIEW

**Review by pawel-kow — CHANGES_REQUESTED** [review]
Filename not as per schema. MX record incomplete.

**Comment by kerolasa** [comment]
Why there are two templates with colliding provider & service Ids?

```
Templates $ dc-template-linter dnsdad.*
2024-03-25T09:30:59Z ERR file name does not use required pattern expected=dnsdad.com.dnsdadrecords.json template=dnsdad.com.hosting.json
2024-03-25T09:30:59Z ERR file name does not use required pattern expected=dnsdad.com.dnsdadrecords.json template=dnsdad.hosting.json
2024-03-25T09:30:59Z ERR duplicate provierId + serviceId detected providerId=dnsdad.com serviceId=dnsdadrecords template=dnsdad.hosting.json
```

**Comment by sagartankw3nuts** [comment]
dnsdad.com we have made many minor changes so now we will create a new
account and upload the template

**Comment by pawel-kow** [comment]
Duplicate of #515? Can this one be closed then?

**Comment by rphilip** [comment]
The variables in the template are shown as "Ipadress" not "IPaddress" (2 d's in address)  Not sure if this was a typo or not but may consider changing to prevent confusion.

**Comment by pawel-kow** [comment]
As per https://github.com/Domain-Connect/Templates/pull/505#issuecomment-2054119626 this PR can be closed.

**Pull request closed without merging**
