### PR TITLE
Please Add template for WP Encryption CDN service

### PR DESCRIPTION
**Pull request by gowebsmarty**

### CODE REVIEW

**Comment by arnoldblinn** [comment]
Let me know if you want your service listed on DomainConnect.org

**Comment by gowebsmarty** [comment]
Thank you so much!. Yes, please list our service on DomainConnect.org

**Comment by arnoldblinn** [comment]
Would need your logo, and a contact email address. Most people use domainconnect@, but this isn't a hard requirement.

**Comment by gowebsmarty** [comment]
We would like to hold the process of having our service listed on DomainConnect and would like to do it in coming months. Will reach back when it's time to do so. Thank you so much!

**Pull request merged**
