### PR TITLE
Entri edits

### PR DESCRIPTION
**Pull request by Thekkedath**
Changes to clickfunnels and the.com template

### CODE REVIEW

**Review by wdbaker-godaddy — COMMENTED** [review]
Should version be incremented to 2 for clickfunnels update?

**Comment by Thekkedath** [comment]
@wdbaker-godaddy thank you for highlighting that. It was actually a miscommunication from the application side regarding the dns record set format which is why we had to update the template. So not sure if we should increment the version as its not actually an update on the application side. If you think we should increment the version number regardless, please let me know and I can make that change

**Comment by wdbaker-godaddy** [comment]
Because you are just changing how the variables are passed, I think it's up to your discretion on updating the version number (to distinguish zones added the "old" or "new" way).  If you had added a new record to the template, let's say, then a new version would definitely be warranted.

**Comment by Thekkedath** [comment]
Thank you for explaining that, it makes sense now. I think we will keep the version number as it is now and will increment if new records are added to the template as you suggested.

**Pull request merged**
