### PR TITLE
Update goentri.com.toast.json

### PR DESCRIPTION
**Pull request by evelyndearaujo-goentri**

### CODE REVIEW

**Review by pawel-kow — CHANGES_REQUESTED** [review]
version number bump

**Review by pawel-kow — COMMENTED** [review]
No need to update version?

**Comment by evelyndearaujo-goentri** [comment]
I prefer to keep version 2 considering the last template was not correct. Thanks for checking...

**Comment by evelyndearaujo-goentri** [comment]
actually, you're right, let me update it on our side.

**Review by pawel-kow — APPROVED** [review]
thx

**Pull request merged**
