### PR TITLE
quicklylaunch.com new template

### PR DESCRIPTION
**Pull request by sac-innovation**
Hi,

Kindly let us know if we can add this template. We are in discussion with GoDaddy Domain Connect team and we are already in this step. We would appreciate if you could guide us if there are incorrect values in the json.

Thank you and kind regards,
Koo Vergara

### CODE REVIEW

**Review by pawel-kow — APPROVED** [review]
LGTM

**Comment by pawel-kow** [comment]
all looks good. if you are ready pls let me or @wdbaker-godaddy know to merge

**Comment by sac-innovation** [comment]
Hi @pawel-kow that's great. After this, how could we test? If there's none, then we're good to merge. Thanks!

**Comment by pawel-kow** [comment]
No way to test it right now other than static schema test, which went through in this case. Merging.

**Pull request merged**
