### PR TITLE
Add Jersey Watch as a Service Provider

### PR DESCRIPTION
**Pull request by nratter**
Thanks in advance for the review and let me know if anything needs to change :)

### CODE REVIEW

**Review by pawel-kow — APPROVED** [review]
LGTM!

**Comment by pawel-kow** [comment]
@bdickson1-godaddy can you take a look pls? For me it's OK but I recall GD pushing back on templates without signing, not sure if it's a firm policy though.

**Comment by nratter** [comment]
Hey guys... just following up here! Would you recommend I modify the template to include signing?

**Comment by pawel-kow** [comment]
Ok, no feedback from GD so I merge this one as well for now.

**Comment by bdickson1-godaddy** [comment]
So yes, it would be recommended (but not required).

Thanks,
Brian

From: Nick Rattermann ***@***.***>
Date: Monday, July 11, 2022 at 11:22 AM
To: Domain-Connect/Templates ***@***.***>
Cc: Brian P. Dickson ***@***.***>, Mention ***@***.***>
Subject: Re: [Domain-Connect/Templates] Add Jersey Watch as a Service Provider (PR #251)
Caution: This email is from an external sender. Please do not click links or open attachments unless you recognize the sender and know the content is safe. Forward suspicious emails to ***@***.***



Hey guys... just following up here! Would you recommend I modify the template to include signing?

**Pull request merged**
