### PR TITLE
Separating Bluehost templates into hosting and email parts

### PR DESCRIPTION
**Pull request by nhandy**
Breaking out hosting and email records into 3 different files per brand/property.
email only
hosting only
hosting and email

### CODE REVIEW

**Comment by csjewell** [comment]
Just so you know, this is a coworker of mine.

**Comment by pawel-kow** [comment]
Pls fix the issues with the file names not matching providerId/serviceId in the template.
```
File name justhost.com.hosting_and_email.json not matching the pattern. Expected justhost.com.hosting.json
File name justhost.com.email.json not matching the pattern. Expected justhost.com.hosting.json
File name fastdomain.com.hosting_and_email.json not matching the pattern. Expected fastdomain.com.hosting.json
File name fastdomain.com.email.json not matching the pattern. Expected fastdomain.com.hosting.json
File name hostmonster.com.email.json not matching the pattern. Expected hostmonster.com.hosting.json
File name bluehost.com.hosting_and_email.json not matching the pattern. Expected bluehost.com.hosting.json
File name bluehost.in.email.json not matching the pattern. Expected bluehost.in.hosting.json
File name hostmonster.com.hosting_and_email.json not matching the pattern. Expected hostmonster.com.hosting.json
File name bluehost.in.hosting_and_email.json not matching the pattern. Expected bluehost.in.hosting.json
File name bluehost.com.email.json not matching the pattern. Expected bluehost.com.hosting.json
```

**Comment by nhandy** [comment]
Forgot to update the schemaId in the new files

**Comment by annreilly** [comment]
Hi Pawel,  are we able to merge these changes now that Nathan fixed the errors

**Pull request merged**
