### PR TITLE
Add goBoost template

### PR DESCRIPTION
**Pull request by jlebron3**

### CODE REVIEW

**Comment by arnoldblinn** [comment]
Do you want goboost listed on domainconnect.org as a Service Provider?

**Comment by jlebron3** [comment]
@arnoldblinn yes and Thank you :)

**Comment by arnoldblinn** [comment]
Happy to do it; although I need a logo (can pull from the template) and an email contact to list on the website (most providers use domainconnect@xxxx.com)

**Comment by pawel-kow** [comment]
Hi @jlebron3 , for template integration at IONOS please reach out to domain_connect_admin@domain.ionos.com

**Pull request merged**
