### PR TITLE
Entri templates

### PR DESCRIPTION
**Pull request by evelyndearaujo-goentri**

### CODE REVIEW

**Review by pawel-kow — APPROVED** [review]
lgtm!

@evelyndearaujo-goentri did you know you can also refer to the same domain in the redirect without using any external variable, just `%fqdn%` ?
```
    {
      "type": "REDIR301",
      "target": "https://www.%fqdn%",
      "host": "@",
      "groupId": "a2"
    },
```

**Comment by evelyndearaujo-goentri** [comment]
> 

I didn't know that, thanks for sharing it @pawel-kow. In the case, the"fqdn" is the root domain, is that right?

**Comment by pawel-kow** [comment]
`%fqdn%` is the full hostname where the template is applied.
If there is no `host` parameter specified, this is the domain name, if `host` is specified than it is the full name of the subdomain.

**Comment by evelyndearaujo-goentri** [comment]
got it, thanks. 

Do you prefer I update the template using the %fqdn% ?

**Pull request merged**
